### ISSUE TITLE
Summarize data button is not activated

### ISSUE THREAD

**Issue by uhaifabioinfo** [dcgemperline/Morpheus_SpC#1]
Hi,

I've installed MSpC and loaded data analyzed using Morpheus. However, I can't get Summarize data button to light up. any suggestions?

Cheers,
David.

**Comment by dcgemperline** [comment]
Hello David,

As long as you have the output files from Morpheus in the same folder where the summary.tsv file is located, the summarize data button should light up. If you're having issues, run Morpheus and leave everything in a single output folder. Select the summary.tsv file and it should work. Let me know if you are still having issues.

David

**Comment by uhaifabioinfo** [comment]
Hi,

All of the .tsv files (along with the other files) are in the same folder – still not working though. Does it matter where the MSpC is installed?

Thanks!

David.

**Comment by dcgemperline** [comment]
Hmm, this is a bit strange. Can you provide the filepath where MSpC is installed, and the filepath where your summary.tsv proteingroups.tsv and psms.tsv files are located? I may be able to see what's going on.

What version of Morpheus are you using as well?

David

**Comment by uhaifabioinfo** [comment]
MScP is in C:\programs\Morpheus\release 1.2.1 The Morpheus build is 255. 

The data is in F:\CPTAC…\JX008_Colon_VU

These are two separate HD’s on the same computer. The .tsv files are all there, but these are aggregate files – each Morpheus search was done on a set of 30 fractions, and so the file names are aggregate_psms.tsv and aggregate_proteingoups.tsv .I guess the aggregate is what throws it off?

Thanks!

David.

**Comment by dcgemperline** [comment]
Definitely that is what throws it off. It is looking strictly for the default naming output of the protein_groups.tsv and psms.tsv files.

Here are the checks.

PsmFile = "PSMs.tsv";
ProteinGroupFile = "protein_groups.tsv";

If you name them something else, then it wouldnt pass the checks that I put in for the UI.

Running Morpheus with a set of fractions is ideally how I handled this instead of handling it in the MSpC software so that you wouldn't have to specify an experimental design file. 

If you have a set of fractions that you would like to summarize you can put all the fractions into a folder. For example, make folders called set1, set2, set3, etc. Re-run the Morpheus search and Morpheus will then summarize and make PSM and protein group files for these aggregate datasets. In the summary.tsv file it will be indicated with a \* after the folder name. set1\* etc. In this case all of the PSMs for those 30 fractions will be summed and reported. So if you have technical replicates you may want to put each set of 30 fractions into two separate folders tech1, tech2. MSpC will report the individual file dNSAF values, and the aggregate \* values as well.

I have not had a chance to update to the latest Morpheus release, but plan on doing so shortly. I know MSpC works well with release 151, but there may be some other bugs associated with the newer morpheus releases. I am working on my dissertation right now, but I may be able to fix any bugs associated relatively quickly if you run into them.

**Comment by uhaifabioinfo** [comment]
OK, I will give it a go. Thanks!

**Comment by dcgemperline** [comment]
Another reason for doing this, is that it controls for the global FDR rate, in that if you ran Morpheus many times with 1% FDR for peptides, proteins, and PSMs, that eventually you would start to include data that was not statistically significant (although this would be small).

Feel free to contact me anytime. I just hope that others find this software useful.
